### PR TITLE
Added method addPromises

### PR DESCRIPTION
**Pull request by alsfurlan**
Hi @ajoslin,

I feel the need about a method which do this and I expect you like and add a promiseTracker. I don't know much about the tests. So a write only a function.

Best Reguards,

### CODE REVIEW

**Comment by alsfurlan** [comment]
@ajoslin Are you alive?

**Comment by ajoslin** [comment]
I am indeed alive! I apologize.

You should just do it this way:

```js
promises.forEach(promiseTracker.addPromise)
```

**Comment by ajoslin** [comment]
Released v2.2.0, addPromise now accepts an array.

**Comment by alsfurlan** [comment]
@ajoslin hahaha. Thanks man! In my work, sometimes we need add many promises.

**Pull request closed without merging**
